### ISSUE TITLE
Type names last letter being cut off in search menu

### ISSUE THREAD

**Issue by peterjamesnugent** [BHoM/BHoM_UI#240] opened 2020-04-07 15:28 UTC
#### Description:

The last letter of some type names are cut off in the search menu.

#### Steps to reproduce:

1. Open the search menu (seems to only occur in Grasshopper) 
2. Search of an oM type e.g. Bar
![image](https://user-images.githubusercontent.com/30078587/78688000-ab504180-78ec-11ea-9a0d-d4a30cf280eb.png)

#### Expected behaviour:

Correct type names to be displayed.

#### Test file(s):

N/A.

**Comment by adecler** [comment] 2020-04-21 03:52
Hmmm, weird. It doesn't happen for me:

![image](https://user-images.githubusercontent.com/16853390/79823378-3db11480-83c6-11ea-90cf-be99968fcd60.png)

**Comment by peterjamesnugent** [comment] 2020-04-21 08:20
This only occurs in Grasshopper for Rhino 5 but not in Grasshopper for Rhino 6. It also does not occur in Excel. Very odd.

**Comment by adecler** [comment] 2020-04-21 08:22
> This only occurs in Grasshopper for Rhino 5 but not in Grasshopper for Rhino 6. It also does not occur in Excel. Very odd.

I am on Rhino 5. Did you meant it the other way around ?

**Comment by peterjamesnugent** [comment] 2020-04-21 08:40
I am using Rhino 5 primarily too. It appears to be local to my machine. A few more notes on what I have noticed:
- It only occurs on type objects
- It does not occur on interfaces (ISectionProperty, ISurfaceProperty)
- It does not occur on Results

**Comment by adecler** [comment] 2020-04-21 09:03
Since  I cannot debug this without it happening on my machine, do you mind having a look ?

Don't worry, It's just a case of putting a breakpoint after the line I have highlighted below and checking the values for the case that cause problem.

![image](https://user-images.githubusercontent.com/16853390/79846599-38b58a80-83f1-11ea-9844-f42ad97b6a9e.png)

The key thing you might want to try is to force the width of the label once we know the maxWidth (line 232). So try to replace that line with the code below to see if it fixes your problem:

```c#
m_Popup.Width = maxWidth;
foreach (Control row in m_SearchResultPanel.Controls)
{
    row.Width = maxWidth;
    row.Controls[1].Width = maxWidth - row.Controls[0].Width;
}
```

**Comment by peterjamesnugent** [comment] 2020-04-21 16:19
I tried putting the code above but it crashes Rhino 5, not Rhino 6. 

I have summarised the outputs from the debugging below. Note the Environments.Elements.Edge displays correctly:

**Search term: "Bar"** `hits[0]`:
| Name | Value | Type|
| -- | -- | --|
| Text | "BH.oM.Structure.Elements.Bar" | string | 
| Width | 303| int|

**Search term: "Bar"** `hits[1]`:
| Name | Value | Type|
| -- | -- | --|
| Text | "BH.oM.Structure.Elements.Bar.Bar() {Node StartNode, Node EndNode, ISectionProperty SectionProperty, Double OrientationAngle, BarRelease Release, and 4 more inputs}" | string | 
| Width | 1665 | int|

**Search term: "Structure.Elements.Edge"** `hits[0]`:
| Name | Value | Type|
 | -- | -- | --|
 | Text | "BH.oM.Structure.Elements.Edge" | string|
| Width | 320| int|

**Search term: "Environment.Elements.Edge"** `hits[0]`:
| Name | Value | Type|
 | -- | -- | --|
 | Text | "BH.oM.Environment.Elements.Edge" | string|
| Width | 354 | int|

**Comment by adecler** [comment] 2020-09-29 04:06
@peter, is it still happening to you ?

**Comment by peterjamesnugent** [comment] 2020-09-29 08:18
Seems to still be an issue in Rhino 5 and only on some select objects.

### Rhino 5
#### `Panel`
![image](https://user-images.githubusercontent.com/30078587/94530472-0d05be80-0233-11eb-8370-63ff07303a5f.png)
#### `Node`
![image](https://user-images.githubusercontent.com/30078587/94530641-476f5b80-0233-11eb-84e2-cb4930c3580c.png)

### Rhino 6
#### `Panel`
![image](https://user-images.githubusercontent.com/30078587/94530970-c369a380-0233-11eb-89fc-270ac95a889e.png)
#### `Node`
![image](https://user-images.githubusercontent.com/30078587/94531051-e09e7200-0233-11eb-97b6-52ad591a2f32.png)

**Comment by adecler** [comment] 2021-02-17 05:35
Closing this for the following reasons:
- it doesn't happen on Rhino 6 which should now be the default version for most people.
- I cannot reproduce this on Rhino 5. 
![image](https://user-images.githubusercontent.com/16853390/108160859-dd454d80-7124-11eb-8b5e-37ad1ba8c954.png)


Happy to reopen if it becomes possible to reproduce the issue.

**Closed by adecler** 2021-02-17 05:35 UTC
Labels: severity:low, type:bug
