### ISSUE TITLE
Grasshopper freeze on startup

### ISSUE THREAD

**Issue by IsakNaslundBh** [BHoM/BHoM_UI#305] opened 2020-09-16 16:17 UTC
#### Description:

Not sure if this is a UI issue or a GH issue, but raising here as most code is centralised.

In some occasions, Grasshopper freeze on startup Looking like this:
![image](https://user-images.githubusercontent.com/22005920/93364061-5f64d980-f848-11ea-95ad-9ff2b65b3b4d.png)

Trying to start it again makes GH load up but with limited functionality. For example:
- CreateObejct component not functioning
- Global search menu not functioning

Restarting Rhino and Grasshopper everything again runs with no issue

#### Steps to reproduce:

Will try to keep an eye out for when this is occurring, but has only happened a few times and have still not been able to spot a pattern.

**Comment by al-fisher** [comment] 2020-09-16 17:28
I just experienced the exact same behaviour. 

- Grasshopper hanging. 
- Rhino responsive and so called `Command: _Grasshopper` again, and Grasshopper opened by same limited BHoM functionality as @IsakNaslundBh notes.
- Close Rhino and restarted - all ran as expected

**Comment by adecler** [comment] 2020-09-17 03:04
After closing and reopening GH as many times I could handle, I was not able to reproduce the bug. 
Next time, can you hook up Visual Studio and check where the process is hanging ?

**Comment by adecler** [comment] 2020-09-17 07:14
Looking at this again, I see there is no progress bar under the Grasshopper splash screen.
Was that progress bar present at any time ? Not sure about you but the BHoM is usually one of the last plugin that GH is loading so a bit surprising not to see a progress bar at all. 

If there was never a progress bar, the only thing I can think of is that some of the pre-processing GH does before loading the plugins (and displaying the progress bar) is causing it to hang. Very weird though as I cannot really of something that would cause it work sometimes and sometimes not. Also unclear why it doesn't happen on my machine despite me having probably open and closed GH more than anyone during the UI development.

**Comment by IsakNaslundBh** [comment] 2020-09-17 07:22
> Looking at this again, I see there is no progress bar under the Grasshopper splash screen.
Was that progress bar present at any time ? Not sure about you but the BHoM is usually one of the last plugin that GH is loading so a bit surprising not to see a progress bar at all.

For me there was a progress bar that filled up and went through all the plugins. This freeze happened after it had filled up. Basically, the progress bar filled up completely, then disappeared, frozen on the screen on the snip.

It does not happen regularly at all for me, just at rare occasions. I wonder if it has anything to do with the log files (do not have anything to back this up, just that that is the only new thing added I can think of)? I have been opening and closing both rhino+GH and excel multiple times throughout the days, not sure if it is some combination of that causing it?

**Comment by alelom** [comment] 2020-09-17 07:53
> It does not happen regularly at all for me, just at rare occasions. 

Same here. I had this only twice yesterday. 

> For me there was a progress bar that filled up and went through all the plugins. This freeze happened after it had filled up. Basically, the progress bar filled up completely, then disappeared, frozen on the screen on the snip.

Same. 
For me, when grasshopper finally opened, components in a script I opened couldn't load, and the CTRL+SHIFT+B menu didn't work.

**Comment by adecler** [comment] 2020-09-17 07:57
PR raised here: #306.

Feel free to add yourself as a reviewer if you also have the problem.

**Comment by IsakNaslundBh** [comment] 2020-09-21 10:08
So, got the error again, whilst on debug on GH, UI, Excel and Dynamo.

Tried attaching both GH and UI, but end up in this screen:

![image](https://user-images.githubusercontent.com/22005920/93753289-36ee2e00-fc00-11ea-8bee-e727e44533a3.png)

Will turn on Native debugging on BHoM_UI and GH and rebuild and check if that means I can get access if I get this again.

I forced open GH again, by hitting the GH load button one more time, and had a look at raised events. I got this:

![image](https://user-images.githubusercontent.com/22005920/93754904-b8df5680-fc02-11ea-8e82-4c6d910f5994.png)

Seem to be complaining abot loading types from a significant portion of the engines. Have serialisaed out the log files here:

[20200921-WarningsOnStartEvents.zip](https://github.com/BHoM/BHoM_UI/files/5254696/20200921-WarningsOnStartEvents.zip)

In case useful. Worth noting that the Reflection_Engine, which is currently executing, is naturally not in the list. Wonder if the dynamic loading of the dlls is somehow playing up, at least when extracting all of the types?

Will continue to have a look out!

**Comment by IsakNaslundBh** [comment] 2020-09-21 13:04
So, did happen again. This time I was on the https://github.com/BHoM/BHoM_Engine/pull/2002 branch, so got a bit more message information.

[20200921-WarningsOnStartEvents2.zip](https://github.com/BHoM/BHoM_UI/files/5255465/20200921-WarningsOnStartEvents2.zip)

Some digging on the web together with @alelom and @al-fisher found dome references to potential race conditions. As the BHoMAnalytics is using the serialiser engine, which is loading up all methods/types at the same time as BHoM_UI is being loaded up, this seems like a possible cause for the issue, as non of those methods are threadsafe.

Have raised an issue on the reflection_Engine here: https://github.com/BHoM/BHoM_Engine/issues/2003 and will raise a PR, putting padlocks in place around the Methods returning MethodLists as well as TypeLists.

**Comment by adecler** [comment] 2020-09-29 02:47
All, can you confirm that this bug has now been solved by the last PR ?

**Closed** 2020-09-29 02:47 UTC
Labels: type:bug

**Comment by IsakNaslundBh** [comment] 2020-09-29 07:28
Have not had the issue since the lock fix. Given that it only happened at rare occasions, I can not be 100% sure, but will reopen this issue if it happens again!
