### ISSUE TITLE
BHoM_UI: Support for display scaling

### ISSUE THREAD

**Issue by michaldengusiak** [BHoM/BHoM_UI#114] opened 2019-07-04 14:40 UTC
Currently when users have scaling different to 100% suffer from display issue [see details here](https://github.com/BHoM/Grasshopper_Toolkit/issues/377)

With more and more 4K screens this will become increasing problem for users... would be worth to think about possible solutions

![image](https://user-images.githubusercontent.com/26113670/60674200-83214700-9e71-11e9-9681-4e2113a01d0b.png)

**Comment by epignatelli** [comment] 2019-07-04 14:51
Some help for the WinForm side:
https://stackoverflow.com/questions/22735174/how-to-write-winforms-code-that-auto-scales-to-system-font-and-dpi-settings

**Comment by adecler** [comment] 2020-01-09 05:21
I couldn't reproduce even after pushing the scale all the way to 175%. 
Feel free to reopen and assign it to yourself but I am closing this for now.

**Closed by adecler** 2020-01-09 05:21 UTC
Labels: type:bug
