### ISSUE TITLE
Internalised Objects Turning into Custom Objects

### ISSUE THREAD

**Issue by kayleighhoude** [BHoM/BHoM_UI#332] opened 2020-11-05 13:43 UTC
#### Description:
Between sessions of opening Grasshopper, the internalised objects turn into custom objects, I have experienced this issue in both Excel and Grasshopper using yesterday's alpha

![image](https://user-images.githubusercontent.com/34316256/98248241-ab77f480-1f42-11eb-9035-3fce0c964269.png)

@michaelhoehn also experienced this issue in Grasshopper

**Comment by adecler** [comment] 2020-11-11 07:52
I cannot reproduce this bug. I have tried with multiple object types, including `Architecture.Elements.Ceiling` both saving of internalised component and duplicates of it. 

I see that the `Ceiling` class was modified 26 days ago without any versioning provided. Since types that cannot be deserialised correctly are turned into `CustomObject`, that seems like the most likely explanation to me.

If that is not the case, can you provide a file that reproduces this issue ?

**Comment by adecler** [comment] 2020-11-12 04:02
Tested with file created on older version of the BHoM from @FraserGreenroyd (can find the file [here](https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/BHoM_UI/CeilingVersioning.gh?csf=1&web=1&e=b0fNqs)) and it all works fine.

Parking this until a failing file is provided.

**Comment by adecler** [comment] 2021-01-06 03:10
Closing as left idle for two months without sufficient information to reproduce the bug

**Closed by adecler** 2021-01-06 03:10 UTC
Labels: status:parked, type:bug
