### ISSUE TITLE
UI Pull not passing Active flag to adapter pull components resulting in hanging data

### ISSUE THREAD

**Issue by travispotterBH** [BHoM/BHoM_UI#422] opened 2022-07-20 14:12 UTC
#### Description:

As discovered by @dengh0 
Using the [daily alpha](https://burohappold.sharepoint.com/sites/BHoM/Installers/Forms/AllItems.aspx?xsdata=MDN8MDF8fDQwMGVmMThkYjAzNTQ5MTE5YzM1NTI0ZDJiYzkxY2RlfDUwZWU2NDE4ODY5ZTQ4ZjVhOTgyMzYwN2ZjZWUxZTFkfDF8MHw2Mzc3NTYxODUzNzk3ODI1MTl8R29vZHxWR1ZoYlhOVFpXTjFjbWwwZVZObGNuWnBZMlY4ZXlKV0lqb2lNQzR3TGpBd01EQWlMQ0pRSWpvaUlpd2lRVTRpT2lJaUxDSlhWQ0k2TVRKOQ%3D%3D&sdata=QzlkNWVGNVZBR1E1NlhwcWtQNnlNSFNHL0VnU0xkYUx4cUljbmhFMkJtZz0%3D&ovuser=50ee6418%2D869e%2D48f5%2Da982%2D3607fcee1e1d%2Ctravis%2Epotter%40burohappold%2Ecom&OR=Teams%2DHL&CT=1640021746492&id=%2Fsites%2FBHoM%2FInstallers%2FDaily%20Alphas%2F220720%5FBuroHappold%5FBHoM%5Fv5%2E3%2Ealpha%2Emsi&parent=%2Fsites%2FBHoM%2FInstallers%2FDaily%20Alphas) 

In Grasshopper and Excel, the pull method appears to be actioning before the Boolean toggle has been applied to the method. See images below. 

![AdapterFunctionsOnFalseActiveStatus](https://user-images.githubusercontent.com/96432552/180002328-eadc264f-3d97-429b-96a3-1f90e09a9452.gif)
![AdapterFunctionsOnFalseActiveStatus2](https://user-images.githubusercontent.com/96432552/180002335-55f1c8dd-c9cb-412c-b069-313ab1b0cfd0.gif)

I am unsure if this is specific to this daily alpha or others versions as well. 

#### Steps to reproduce:

Build a file adapter, pull request and attempt to pull in both grasshopper and excel. 

#### Expected behaviour:

It is expected that the pull method would only action once the boolean toggle is marked as "True."

#### Test file(s):

https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?newTargetListUrl=%2Fsites%2FBHoM%2F02%5FCurrent&viewpath=%2Fsites%2FBHoM%2F02%5FCurrent%2FForms%2FAllItems%2Easpx&isAscending=true&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FIssue%2FBHoM%2FBHoM%5FAdapter%2F%23322%20Pull%20Methods%20Action%20on%20Active%20status%20of%20False&sortField=LinkFilename&viewid=a5a93cba%2Dfcca%2D46cc%2Da31a%2D80b8d5cbfd7b

**Comment by FraserGreenroyd** [comment] 2022-07-22 15:42
On my investigation just now, I've identified the culprit to be this method in the `Pull.cs` component within BHoM_UI:

```
protected override bool ShouldCalculateNewResult(List<object> inputs, ref object result)
{
    return (bool)inputs.Last() == true;
}
```

When we toggle that to `false` we decide we shouldn't calculate a new result, which means the old result is returned for the same adapter. It's a speed saver by the looks of it, caching the output so that you can turn off the adapter pull (e.g. if you've pulled from a large file or open model) but keep your results without losing them.

So on that basis, this actually looks like a by design issue that can be confusing but makes sense when you consider the original development case (large models being pulled from live models rather than files). In that case, having a Revit pull set up for example, and then moving an object in Revit, would retrigger the pull immediately because they're connected with sockets. For a large model, that could be minutes of Grasshopper (or Excel) locking up when the move in Revit might be small, or even a mistake and needs to be undone. In this case, turning off the pull (active == `false`) but caching the output allows the output to continue to be used without the pull being retriggered until the user is ready.

So in this case I'm inclined to suggest we either need to maybe improve some documentation to make that more obvious, or do a bigger workshop on the desired outcome of the scenario, or leave it as is.

**Comment by FraserGreenroyd** [comment] 2022-11-09 10:26
Following review, this has been deemed to be accepted behaviour, and better communications with users is the solution. Issue closed as no work to be undertaken.

**Closed by FraserGreenroyd** 2022-11-09 10:26 UTC
Labels: type:bug, priority:low
